CREATE PROC FI_SP_IncBeneficiarios
	@NOME          VARCHAR(50),
    @CPF		   VARCHAR(14),
    @IDCLIENTE     VARCHAR(50)
AS
BEGIN
INSERT INTO CLIENTES(NOME, CPF, IDCLIENTE)
VALUES(@NOME, @CPF, @IDCLIENTE)

SELECT SCOPE_IDENTITY()
END