SELECT C.NOME, C.SOBRENOME, C.NACIONALIDADE, C.CPF, C.CEP, C.ESTADO, C.CIDADE, C.LOGRADOURO, C.EMAIL, C.TELEFONE, C.ID,
			   B.CPF, B.NOME, B.IDCLIENTE, B.ID
		FROM CLIENTES C, BENEFICIARIOS B
		WITH(NOLOCK)
		WHERE C.ID = B.IDCLIENTE 
		AND C.ID = 18